# Refer to the README.md file in within this service directory to configure all ssm parameters required for this service.
service: app-api

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  - serverless-associate-waf
  - serverless-offline
  - serverless-stack-termination-protection
  - serverless-idempotency-helper
  - serverless-iam-helper
  - serverless-s3-bucket-helper
  - serverless-api-client-certificate
  - "@enterprise-cmcs/serverless-waf-plugin"

s3BucketHelper:
  loggingConfiguration:
    destinationBucketName: ${env:loggingBucket, ssm:/configuration/${self:custom.stage}/s3/accessLogsBucket, ssm:/configuration/default/s3/accessLogsBucket}
    logFilePrefix: ${env:loggingBucket, ssm:/configuration/${self:custom.stage}/s3/accessLogsPrefix, ssm:/configuration/default/s3/accessLogsPrefix}

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  wafPlugin:
    name: ${self:service}-${self:custom.stage}-webacl-waf
  wafExcludeRules:
    awsCommon:
      - "SizeRestrictions_BODY"
  serverlessTerminationProtection:
    stages:
      - main
      - val
      - production
  dotenv:
    path: ../../.env
  accountId: ${AWS::AccountId}
  acsTableName: ${env:acsTableName, cf:database-${self:custom.stage}.AcsTableName}
  acsTableArn: ${env:acsTableArn, cf:database-${self:custom.stage}.AcsTableArn}
  fmapTableName: ${env:fmapTableName, cf:database-${self:custom.stage}.FmapTableName}
  fmapTableArn: ${env:fmapTableArn, cf:database-${self:custom.stage}.FmapTableArn}
  stateTableName: ${env:stateTableName, cf:database-${self:custom.stage}.StateTableName}
  stateTableArn: ${env:stateTableArn, cf:database-${self:custom.stage}.StateTableArn}
  stateStatusTableName: ${env:stateStatusTableName, cf:database-${self:custom.stage}.StateStatusTableName}
  stateStatusTableArn: ${env:stateStatusTableArn, cf:database-${self:custom.stage}.StateStatusTableArn}
  sectionTableName: ${env:sectionTableName, cf:database-${self:custom.stage}.SectionTableName}
  sectionTableArn: ${env:sectionTableArn, cf:database-${self:custom.stage}.SectionTableArn}
  sectionBaseTableName: ${env:sectionBaseTableName, cf:database-${self:custom.stage}.SectionBaseTableName}
  sectionBaseTableArn: ${env:sectionBaseTableArn, cf:database-${self:custom.stage}.SectionBaseTableArn}
  stageEnrollmentCountsTableName: ${env:stageEnrollmentCountsTableName, cf:database-${self:custom.stage}.StageEnrollmentCountsTableName}
  stageEnrollmentCountsTableArn: ${env:stageEnrollmentCountsTableArn, cf:database-${self:custom.stage}.StageEnrollmentCountsTableArn}
  webAclName: ${self:service}-${self:custom.stage}-webacl-waf
  uploadsTableName: ${env:uploadsTableName, cf:database-${self:custom.stage}.UploadsTableName}
  uploadsTableArn: ${env:uploadsTableArn, cf:database-${self:custom.stage}.UploadsTableArn}
  docraptorApiKey: ${env:docraptorApiKey, ssm:/${self:custom.stage}/pdf/docraptorApiKey, ssm:/default/pdf/docraptorApiKey}
  associateWaf:
    name: ${self:custom.webAclName}
    version: V2
  fiscalBucketEnvMap:
    production: production
    val: val
    main: main
    default: main
  fiscalBucketEnv: ${self:custom.fiscalBucketEnvMap.${self:custom.stage}, self:custom.fiscalBucketEnvMap.default}
  serverlessApiClientCertificate:
    rotateCerts: true
    daysLeft: 30
  warmup:
    default:
      enabled: true
      prewarm: true
      events:
        - schedule: rate(${env:warmupSchedule, ssm:/configuration/${self:custom.stage}/warmup/schedule, ssm:/configuration/default/warmup/schedule, "60 minutes"})
      concurrency: ${env:warmupConcurrency, ssm:/configuration/${self:custom.stage}/warmup/concurrency, ssm:/configuration/default/warmup/concurrency, 5}
  authValue:
    main: aws_iam
    master: aws_iam
    val: aws_iam
    prod: aws_iam
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  tracing:
    apiGateway: true
  logs:
    restApi: true
  iam:
    role:
      path: ${env:iamPath, ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: ${env:iamPermissionsBoundary, ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: "*"
        - Effect: "Allow"
          Action:
            - ssm:GetParameter
          Resource: "*"
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: !Sub arn:aws:s3:::uploads-${self:custom.fiscalBucketEnv}-carts-download-${AWS::AccountId}/*
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource: !Sub arn:aws:s3:::uploads-${self:custom.stage}-attachments-${AWS::AccountId}/*
  environment:
    acsTableName: ${self:custom.acsTableName}
    fiscalYearTemplateS3BucketName: ${env:fiscalYearTemplateBucketName, ssm:/configuration/${self:custom.stage}/s3/fiscalYearTemplateBucket, ssm:/configuration/default/s3/fiscalYearTemplateBucket, ""}
    fmapTableName: ${self:custom.fmapTableName}
    docraptorApiKey: ${self:custom.docraptorApiKey}
    stateTableName: ${self:custom.stateTableName}
    stateStatusTableName: ${self:custom.stateStatusTableName}
    sectionTableName: ${self:custom.sectionTableName}
    sectionBaseTableName: ${self:custom.sectionBaseTableName}
    stageEnrollmentCountsTableName: ${self:custom.stageEnrollmentCountsTableName}
    uploadsTableName: ${self:custom.uploadsTableName}
    uploadS3BucketName: !Sub ${env:attachmentsBucketName, "uploads-${self:custom.stage}-attachments-${AWS::AccountId}"}
    stage: ${self:custom.stage}

functions:
  getStates:
    handler: handlers/state/get.getStates
    events:
      - http:
          path: state
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  getEnrollmentCounts:
    handler: handlers/enrollmentCounts/get.getEnrollmentCounts
    events:
      - http:
          path: enrollment_counts/{year}/{state}
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  getFiscalYearTemplateLink:
    handler: handlers/fiscalYearTemplate/get.getFiscalYearTemplateLink
    events:
      - http:
          path: fiscalYearTemplate
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  getStateStatus:
    handler: handlers/stateStatus/get.getStateStatus
    events:
      - http:
          path: state_status
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  updateStateStatus:
    handler: handlers/stateStatus/update.updateStateStatus
    events:
      - http:
          path: state_status/{year}/{state}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  getSections:
    handler: handlers/section/get.getSections
    events:
      - http:
          path: section/{year}/{state}
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  updateSections:
    handler: handlers/section/update.updateSections
    events:
      - http:
          path: save_report/{year}/{state}
          method: put
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  generateFormTemplates:
    handler: handlers/formTemplates/post.post
    timeout: 30
    events:
      - http:
          path: formTemplates
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  postUpload:
    handler: handlers/uploads/createUploadPsUrl.psUpload
    events:
      - http:
          path: psUrlUpload/{year}/{state}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  postDownload:
    handler: handlers/uploads/createDownloadPsUrl.getSignedFileUrl
    events:
      - http:
          path: psUrlDownload/{year}/{state}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  deleteUpload:
    handler: handlers/uploads/delete.deleteUpload
    events:
      - http:
          path: uploads/{year}/{state}
          method: delete
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  viewUploads:
    handler: handlers/uploads/viewUploaded.viewUploaded
    events:
      - http:
          path: uploads/{year}/{state}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  printPdf:
    handler: handlers/printing/printPdf.print
    timeout: 30
    events:
      - http:
          path: print_pdf
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref ApiGatewayRestApi
  Outputs:
    ApiGatewayRestApiName:
      Value: !Ref ApiGatewayRestApi
    ApiGatewayRestApiUrl:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}
    Region:
      Value: !Sub ${AWS::Region}
