env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - recommended/esnext
  - recommended/node
  - 'plugin:@typescript-eslint/recommended'

rules:
  no-const-assign: error
  no-duplicate-imports: error
  no-unreachable: error
  no-unused-vars: error
  no-console: error
  no-empty: error
  no-extra-semi: error
  multiline-comment-style:
    - error
    - starred-block
