repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.11.0
    hooks:
      - id: eslint
        files: '\.[jt]sx?$' # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint
          - typescript-eslint
          - eslint-plugin-jest@26.1.3
          - eslint-plugin-cypress@2.12.1
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        files: '\.[jt]sx?$' # *.js, *.jsx, *.ts and *.tsx
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ['--exclude-files', 'services/uploads/src/test.json']
