service: database

frameworkVersion: "3"

plugins:
  - serverless-dynamodb-local
  - serverless-stack-termination-protection
  - serverless-s3-bucket-helper
  - serverless-plugin-scripts
  - serverless-offline

s3BucketHelper:
  loggingConfiguration:
    destinationBucketName: ${env:loggingBucket, ssm:/configuration/${self:custom.stage}/s3/accessLogsBucket, ssm:/configuration/default/s3/accessLogsBucket}
    logFilePrefix: ${env:loggingBucket, ssm:/configuration/${self:custom.stage}/s3/accessLogsPrefix, ssm:/configuration/default/s3/accessLogsPrefix}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - main
      - master
      - val
      - production
  acsTableName: ${self:custom.stage}-acs
  fmapTableName: ${self:custom.stage}-fmap
  stateTableName: ${self:custom.stage}-state
  stateStatusTableName: ${self:custom.stage}-state-status
  sectionTableName: ${self:custom.stage}-section
  sectionBaseTableName: ${self:custom.stage}-section-base
  stageEnrollmentCountsTableName: ${self:custom.stage}-stg-enrollment-counts
  uploadsTableName: ${self:custom.stage}-uploads
  seedOptions:
    prod: false
    val: false
    default:
      domain:
        sources:
          - table: ${self:custom.acsTableName}
            sources: [./seed-acs.json]
          - table: ${self:custom.fmapTableName}
            sources: [./seed-fmap.json]
          - table: ${self:custom.stateTableName}
            sources: [./seed-state.json]
          - table: ${self:custom.stateStatusTableName}
            sources: [./seed-status.json]
          - table: ${self:custom.sectionTableName}
            sources: [./seed-section.json]
          - table: ${self:custom.sectionBaseTableName}
            sources: [./seed-section-base.json]
          - table: ${self:custom.stageEnrollmentCountsTableName}
            sources: [./seed-stg-enrollment-counts.json]
  dataMigrationEnabled: ${env:runV2DataMigration, ssm:/configuration/${self:custom.stage}/runV2DataMigration, ssm:/configuration/default/runV2DataMigration}
  dataMigrationEnvMap:
    production: prod
    val: staging
    main: master
    default: master
  dataMigrationEnv: ${self:custom.dataMigrationEnvMap.${self:custom.stage}, self:custom.dataMigrationEnvMap.default}
  scripts:
    hooks:
      deploy:finalize: |
        if [ ${self:custom.dataMigrationEnabled} = "true" ];
        then
          serverless invoke --stage ${self:custom.stage} --function dataMigration
        fi
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed: ${self:custom.seedOptions.${self:custom.stage}, self:custom.seedOptions.default}
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      path: ${env:iamPath, ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: ${env:iamPermissionsBoundary, ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  dataMigration:
    handler: handlers/dataMigration/dataMigration.handler
    environment:
      postgresDb: ${env:postgresDatabase, ssm:/${self:custom.dataMigrationEnv}/postgres_db}
      postgresHost: ${env:postgresHost, ssm:/${self:custom.dataMigrationEnv}/postgres_host}
      postgresUser: ${env:postgresUser, ssm:/${self:custom.dataMigrationEnv}/postgres_user}
      postgresPassword: ${env:postgresPassword, ssm:/${self:custom.dataMigrationEnv}/custom/postgres_custom_password, ssm:/${self:custom.dataMigrationEnv}/postgres_password}
      dynamoPrefix: ${self:custom.stage}
    timeout: 120
    vpc:
      securityGroupIds:
        - ${env:runV2DataMigration, ssm:/configuration/${self:custom.stage}/migrationSecurityGroup, ssm:/configuration/default/migrationSecurityGroup}
      subnetIds:
        - ${env:runV2DataMigration, ssm:/configuration/${self:custom.stage}/migrationSubnet, ssm:/configuration/default/migrationSubnet}

resources:
  Resources:
    AcsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.acsTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: stateId
            AttributeType: S
          - AttributeName: year
            AttributeType: N
        KeySchema:
          - AttributeName: stateId
            KeyType: HASH
          - AttributeName: year
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    FmapTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.fmapTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: fiscalYear
            AttributeType: N
          - AttributeName: stateId
            AttributeType: S
        KeySchema:
          - AttributeName: fiscalYear
            KeyType: HASH
          - AttributeName: stateId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    StateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stateTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    StateStatusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stateStatusTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: year
            AttributeType: N
          - AttributeName: stateId
            AttributeType: S
        KeySchema:
          - AttributeName: stateId
            KeyType: HASH
          - AttributeName: year
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    SectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.sectionTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sectionId
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sectionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    SectionBaseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.sectionBaseTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: year
            AttributeType: N
          - AttributeName: sectionId
            AttributeType: N
        KeySchema:
          - AttributeName: year
            KeyType: HASH
          - AttributeName: sectionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    StageEnrollmentCountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stageEnrollmentCountsTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: entryKey
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: entryKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    UploadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.uploadsTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: uploadedState
            AttributeType: S
          - AttributeName: fileId
            AttributeType: S
        KeySchema:
          - AttributeName: uploadedState
            KeyType: HASH
          - AttributeName: fileId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
  Outputs:
    AcsTableName:
      Value: !Ref AcsTable
    AcsTableArn:
      Value: !GetAtt AcsTable.Arn
    FmapTableName:
      Value: !Ref FmapTable
    FmapTableArn:
      Value: !GetAtt FmapTable.Arn
    StateTableName:
      Value: !Ref StateTable
    StateTableArn:
      Value: !GetAtt StateTable.Arn
    StateStatusTableName:
      Value: !Ref StateStatusTable
    StateStatusTableArn:
      Value: !GetAtt StateStatusTable.Arn
    SectionTableName:
      Value: !Ref SectionTable
    SectionTableArn:
      Value: !GetAtt SectionTable.Arn
    SectionBaseTableName:
      Value: !Ref SectionBaseTable
    SectionBaseTableArn:
      Value: !GetAtt SectionBaseTable.Arn
    StageEnrollmentCountsTableName:
      Value: !Ref StageEnrollmentCountsTable
    StageEnrollmentCountsArn:
      Value: !GetAtt StageEnrollmentCountsTable.Arn
    UploadsTable:
      Value: !Ref UploadsTable
    UploadsTableArn:
      Value: !GetAtt UploadsTable.Arn
    Region:
      Value: !Sub ${AWS::Region}
