service: carts-seds-ses

frameworkVersion: "2"

plugins:
  - serverless-iam-helper
  - serverless-s3-bucket-helper

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iam:
    role:
      path: ${ssm:/configuration/${self:custom.stage}/iam/path~true, ssm:/configuration/default/iam/path~true, "/"}
      permissionsBoundary: ${ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy~true, ssm:/configuration/default/iam/permissionsBoundaryPolicy~true, ""}

custom:
  stage: ${opt:stage, self:provider.stage}
