name: Pull-request

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v2.0.2
  jest-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Prepare for Jest (frontend)
        run: yarn install --frozen-lockfile
        working-directory: ./services/ui-src
      - name: Jest (frontend)
        run: yarn test
        working-directory: ./services/ui-src
  jest-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Prepare for Jest (backend)
        run: yarn install --frozen-lockfile
        working-directory: ./services/app-api
      - name: Jest (backend)
        run: yarn test
        working-directory: ./services/app-api
  assignAuthor:
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assign PR to Creator
        run: gh pr edit $PRNUM --add-assignee $PR_AUTHOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
