name: Pull-request

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
  jest-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Prepare for Jest (frontend)
        run: yarn install --frozen-lockfile
        working-directory: ./services/ui-src
      - name: Jest (frontend)
        run: yarn test
        working-directory: ./services/ui-src
  jest-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Prepare for Jest (backend)
        run: yarn install --frozen-lockfile
        working-directory: ./services/app-api
      - name: Jest (backend)
        run: yarn test
        working-directory: ./services/app-api
  assignAuthor:
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assign PR to Creator
        run: gh pr edit $PRNUM --add-assignee $PR_AUTHOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}

  #Notify the integrations channel only when a Snyk auto merge fails pr checks
  notify_on_pr_failure:
    runs-on: ubuntu-latest
    needs: 
      - linting
      - jest-frontend
      - jest-backend
    #only check branch names that begin with snyk-
    if: ${{ failure() && startsWith(github.head_ref, 'snyk-') }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ":boom: A Synk auto merge has failed pull request checks in ${{ github.repository }}."
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.INTEGRATIONS_SLACK_WEBHOOK }}
