name: schema validation

on:
  pull_request:
    paths:
      - 'docs/section-schemas/**.json'

jobs:
  schema_validation:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: pip install jsonschema jsonpath_ng
      - name: validate all documents
        run: ./.github/workflows/schema.sh
