name: style checks

on: [pull_request]

jobs:
  prettier:
    name: prettier has been run on compatible files
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - name: check that modified files are prettier
        run: npx prettier $(git diff --diff-filter=ACMR --name-only --relative origin/master -- | xargs) -c -u
  eslint:
    name: frontend linting
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - name: install dependencies
        working-directory: frontend/react
        run: npm install
      - name: run eslint
        working-directory: frontend/react
        run: npx eslint $(git diff --diff-filter=ACMR --name-only --relative origin/master -- . | grep .js$ | xargs)
  black:
    name: python files have been formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: psf/black@d038a24ca200da9dacc1dcb05090c9e5b45b7869
        with:
          options: --check --line-length 79 --skip-string-normalization
